import { dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { FlatCompat } from "@eslint/eslintrc";

/**
 * Flat config, run through the ESLint CLI. `next lint` is deprecated and is
 * removed in Next 16.
 *
 * `eslint-config-next` is still an eslintrc-style config, so it comes in
 * through `FlatCompat`. It also permits a `@typescript-eslint` v5 resolution,
 * and those versions crash on ESLint 9 while loading `no-unused-expressions` —
 * which is why this project pins the v8 plugin and parser directly even though
 * nothing imports them.
 */
const compat = new FlatCompat({
  baseDirectory: dirname(fileURLToPath(import.meta.url)),
});

const config = [
  {
    ignores: [
      ".next/**",
      "target/**",
      // Generated by Codama. Regenerate rather than lint-fixing.
      "clients/**",
      "next-env.d.ts",
    ],
  },
  ...compat.extends("next/core-web-vitals", "next/typescript"),
  {
    rules: {
      /* Apostrophes in editorial copy are written as characters, not as HTML
         entities, because this codebase has a lot of prose. */
      "react/no-unescaped-entities": "off",
      /* Profile and cover images come from arbitrary Arweave/IPFS gateways, so
         next/image would need an open remotePatterns allowlist — which removes
         the optimization it exists to provide. */
      "@next/next/no-img-element": "off",
    },
  },
];

export default config;
